### ISSUE TITLE
Interface Humidity Sensor

### ISSUE THREAD

**Issue by akshita-bhasin** [cu-ecen-5013/s20-environmental-monitoring-tiva#1]
Interfacing sensor using the I2C driver - Linux to the BBB.
**DoD**: Able to read data from the sensor and tested on BBB
1. Figure out interfacing of sensor with development board.
2. Initially test the working of sensor with Arduino. 
3. Interface with Beagle Bone Black.

**Comment by madhukararora** [comment]
Finished reading the data sheet of the sensor and tested the working of sensor with Arduino.

**Comment by madhukararora** [comment]
Facing an issue to get the driver to read from the sensor. Added delay as per the datasheet, still nothing read.

**Comment by madhukararora** [comment]
Blocker : The sensor burned out. Tested on Arduino to verify.

**Comment by akshita-bhasin** [comment]
Closing this task because of what's mentioned in [#14](https://github.com/cu-ecen-5013/final-project-akshita-bhasin/issues/14)
