### ISSUE TITLE
Implement Semaphore/mutex on FreeRTOS

### ISSUE THREAD

**Issue by akshita-bhasin** [cu-ecen-5013/s20-environmental-monitoring-tiva#2]
Use similar algorithm as #3 to implement mutexes and handle shared resources.

**DoD**: Have two running operations to test semaphore/mutex functionality.

**Comment by madhukararora** [comment]
Created two tasks which calculate multiple of 2 and 7 respectively using Mutex and Semaphores in FreeRTOS. 

Screenshot attached to verify. 
**DoD Verified**
![MutexSemaphore Trial](https://user-images.githubusercontent.com/55379299/79671308-b32ea200-8186-11ea-8666-b0aa1c5a2c30.PNG)

[Commit Representing Working of Mutex / Semaphores on TIVA](https://github.com/cu-ecen-5013/s20-environmental-monitoring-tiva/tree/8e52e3b636b898c776de72a65b5004c391f6230b)
